server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由。
      routes:
        - id: payment_routh # payment_routh    路由的ID，没有固定规则但要求唯一，建议配合服务名。
#          uri: http://localhost:8001 #匹配后提供服务的路由地址。
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的就行路由。

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
            - After=2020-07-03T11:33:35.860+08:00[Asia/Shanghai]
#            - Cookie=username, lvyue
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true # 表示是否将自己注册进Eureka-Server，默认为true。
      fetch-registry: true # 是否从Eureka-Server抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
      defaultZone: http://eureka7001.com:7001/eureka
